# Generated by Django 2.2.6 on 2019-10-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='free',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
