# Generated by Django 2.2.6 on 2019-10-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_car_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='free',
            field=models.BooleanField(default=True),
        ),
    ]
